package com.ainq.caliphr.persistence.enums.subtype.caliphrDb;
/**
 * Defines the PatientInfoSubclassType enumeration.
 * 
 * @author autogenerated
 *
 */
public enum PatientInfoSubclassType {

	/** Enum Constant. */
	NOT_A_CHILD,
	/** Enum Constant. */
	PATIENT_INFO_SECURE;

}
