package com.ainq.caliphr.persistence.enums.subtype.caliphrDb;
/**
 * Defines the PatientPhoneNumberSubclassType enumeration.
 * 
 * @author autogenerated
 *
 */
public enum PatientPhoneNumberSubclassType {

	/** Enum Constant. */
	NOT_A_CHILD,
	/** Enum Constant. */
	PATIENT_PHONE_NUMBER_SECURE;

}
