
# Set the error path
error.path: /error

# Logging
logging.level.org.springframework.web: DEBUG

# THYMELEAF (ThymeleafAutoConfiguration)
spring:
  thymeleaf:
    cache: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: 
    mode: LEGACYHTML5
    prefix: /WEB-INF/views/
    suffix: .html
    template-resolver-order: 1
    view-names: "*"

# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: locale/messages
    cache-seconds: -1
    encoding: UTF-8
    fallback-to-system-locale: true

# File upload max size limit and total request size for a multipart/form-data
multipart:
  maxFileSize: 200Mb
  maxRequestSize: 200Mb
  fileSizeThreshold: 1Mb

